### ISSUE TITLE
Inconsistency between Travis and local deploy

### ISSUE THREAD

**Issue by hroncok** [pyvec/elsa#14]
On Travis:

 * gh-pages is not pulled and a single commit is force pushed, the branch will have only one commit

Locally:

 * depending on your local state, the commit will be added on the top of gh-pages branch and force pushed

We can do one of the following:

 * fetch and reset before we commit (resulting in a history of deployments in gh-pages)
 * always remove the branch before committing (resulting in a single commit in gh-pages, consistent with README)

**Comment by encukou** [comment]
Or we can make it configurable.

I'd opt for keeping single commit, or defaulting to that.

**Comment by hroncok** [comment]
I've decided making it configurable would add an unnecessary complexity for almost no reason. Went with the documented behavior.

**Comment by hroncok** [comment]
Deleting the local branch is not enough. ghp-import checks origin/gh-pages and rebases on top of that https://github.com/davisp/ghp-import/blob/3fd376d66d1626da00c623193ff04169afb9c97f/ghp_import.py#L69

**Comment by hroncok** [comment]
It would need to do something like `rm .git/refs/remotes/origin/gh-pages` if `origin` is the right remote.
