### ISSUE TITLE
Artwork proposal

### ISSUE THREAD

**Issue by hroncok** [pyvec/elsa#24]
I've been procrastinating and I've created some Elsa artwork following [this tutorial](http://easydrawingtutorials.com/index.php/disney/261-draw-elsa-frozen) in Inkscape to replace the proprietary image in README. Do others think we could use it? I think it's legally more OK than the current image but on the other hand this time we would host it in the repo.

-----------

(images removed to stay safe)

**Comment by encukou** [comment]
This is going from "random internet image linked from the README" to "project logo", and I think it would be wise to avoid Disney IP entirely.
Could this be a more generic image? Snowflake? Castle? Sled?

**Comment by hroncok** [comment]
I thought so :D

**Comment by hroncok** [comment]
![drawing4](https://cloud.githubusercontent.com/assets/2401856/23254294/d6d1f9a0-f9b7-11e6-99e0-7dff6206086d.png)

?

**Comment by etellwen** [comment]
Tadaaaaaah, what do you think?


![elsalogo svg](https://user-images.githubusercontent.com/29354075/27011233-d6e79c1a-4eb7-11e7-8412-4cd4bf081630.png)

**Comment by encukou** [comment]
Super! Myslím že se to dá hned použít. Kdybys na tom chtěla pracovat dál, zeptal bych se:
- Jak to vypadá zmenšené -- bude potřeba udělat nějakou variaci pro velikosti jako 16x16px?
- Jak by to vypadalo bez toho černého okraje?

**Comment by etellwen** [comment]
This is how it looks without the black outline. I think it doesn't look good. Especially the snowflake isn't visible on light backgrounds. Colours could be changed, but I still don't like it without the outline.

![elsalogo-noline svg](https://user-images.githubusercontent.com/29354075/27984826-c537248a-63df-11e7-990d-f0121f1fdd07.png)

**Comment by etellwen** [comment]
Cca to 64px it's quite alright. 32px and 16px is useless.

![elsalogo16 svg](https://user-images.githubusercontent.com/29354075/27984848-8e1e03e6-63e0-11e7-8e7e-b78b43ec5a1d.png)
![elsalogo32 svg](https://user-images.githubusercontent.com/29354075/27984847-8e1de78a-63e0-11e7-917d-56c816cec854.png)
![elsalogo64 svg](https://user-images.githubusercontent.com/29354075/27984850-8e206a28-63e0-11e7-9f77-01dc64214cba.png)
![elsalogo128 svg](https://user-images.githubusercontent.com/29354075/27984849-8e1e3ed8-63e0-11e7-9ef5-96345f79224b.png)

However, when we'll need such small resolution, we can use a simple snowfake without the text. Or use letter E in blue.

**Comment by etellwen** [comment]
What about blue outline? The colours feel a little different, not sure if better or not.


![elsalogo svg](https://user-images.githubusercontent.com/29354075/27984978-15902f1e-63e3-11e7-9e74-c2f0f17893bd.png) ![elsalogo blueline svg](https://user-images.githubusercontent.com/29354075/27984979-15985680-63e3-11e7-94ad-0ab84224822a.png)

**Comment by frenzymadness** [comment]
Left one, for me
