### ISSUE TITLE
I do no longer see AppVeyor integration here

### ISSUE THREAD

**Issue by hroncok** [pyvec/elsa#38]
The [AppVeyor builds are running](https://ci.appveyor.com/project/encukou/elsa/history), but I don't see the results next to PRs, commits, etc.

Similar issue to https://github.com/pyvec/naucse.python.cz/issues/148

**Comment by encukou** [comment]
I've granted AppVeyor access to Pyvec repos. Gotta run now; let me know if this solves the issue.
Thanks!

**Comment by hroncok** [comment]
It did. Thanks.
