### ISSUE TITLE
Set TEMPLATES_AUTO_RELOAD by default

### ISSUE THREAD

**Issue by encukou** [pyvec/elsa#5]
Should we set `app.config['TEMPLATES_AUTO_RELOAD']` to True by default?

Flask defaults to False because it's slower, but elsa apps are only served for debugging, and speed isn't that important when freezing.

**Comment by hroncok** [comment]
Seems reasonable, at least we do it on all websites. Feel free to do it.

**Comment by hroncok** [comment]
Thanks
