### ISSUE TITLE
Filename extension of 'api.geojson' (type application/octet-stream) does not match Content-Type: application/json

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/elsa#58]
Elsa is not able to recognize a correct media type for GeoJSON. What is the solution / workaround to this? Whatever I do in my code, Elsa will still consider `.geojson` files as `application/octet-stream`.

**Comment by honzajavorek** [comment]
Workaround is to serve it with `.json` 😞

**Comment by hroncok** [comment]
I think it's the mime thing that reports it as ocet stream. The proper long
term solution would be to send a PR to xdg's shared mine info.

I'm on cell phone only with very bad connection, I can provide links later.

Dne so 8. 9. 2018 11:44 uživatel Honza Javorek <notifications@github.com>
napsal:

**Comment by encukou** [comment]
Does GitHub Pages serve the .json extension as geojson?
If yes, I wonder what mapping they use. Elsa should use it as well.

**Comment by hroncok** [comment]
Frozen-Flask uses the [mimetypes](https://docs.python.org/3/library/mimetypes.html) module from Python.

This is what I get:

```pycon
>>> import mimetypes
>>> mimetypes.guess_type('g.geojson')
('application/geo+json', None)
```

Is this a macOS only thing again? What do you get on macOS?

**Comment by hroncok** [comment]
I was wondering if brew installing `shared-mime-info` would make the macOS mimetypes more comprehensive. However as I recently updated to a non yet released Fedora version, there is a mishmash of the kernel version and the VirtualBox kernel module version so I cannot try it right now. Was about to guide @honzajavorek trough the test, but wanted to get the output of `mimetypes.guess_type('g.geojson')` on macOS as is.

**Comment by encukou** [comment]
I have a Mac user next to me :)
The output is `(None, None)`.

**Comment by hroncok** [comment]
Assuming the python is installed via homebrew, does installing shared-mime-info change that?

**Comment by encukou** [comment]
It's not homebrew.
I guess we need @honzajavorek now.

**Comment by hroncok** [comment]
Hehe. Anyway does installing shared-mime-info form homebrew change that (even if python is compiled form source/whatnot)?

**Comment by honzajavorek** [comment]
I installed shared-mime-info by brew and no Python on my machine produces
anything else than None, None

**Comment by hroncok** [comment]
And if you run `update-mime-database $HOME/.local/share/mime`?

**Comment by hroncok** [comment]
Or maybe `sudo update-mime-database /usr/local/share/mime` or something like that? I cannot realy get heads on now.

**Comment by hroncok** [comment]
Maybe this won't help at all. Apparently, Python's mimetypes look into files in [mimetypes.knownfiles](https://docs.python.org/3/library/mimetypes.html#mimetypes.knownfiles) and shared-mime-info does not modify that.

I have `application/geo+json				geojson` in `/etc/mime.types` and macOS apparently does not have that in such file.

Elsa or Frozen-Flask could in theory supply it's own `mime.types` override file. But that seems a bit overcomplicated.

**Comment by hroncok** [comment]
As an immediate workaround, you can use [mimetypes.add_type](https://docs.python.org/3/library/mimetypes.html#mimetypes.add_type) in the projects where this bites you.

**Comment by hroncok** [comment]
> Does GitHub Pages serve the .json extension as geojson?

```console
$ http https://python.cz/static/data/business.geojson
HTTP/1.1 200 OK
...
Content-Type: application/geo+json
...
```

**Comment by honzajavorek** [comment]
The workaround in https://github.com/pyvec/elsa/issues/58#issuecomment-420065000 helps! Thanks!
