### ISSUE TITLE
Base URL with path causes problems

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/elsa#59]
Example:

```
cli(app, base_url='https://honzajavorek.github.io/map')
```

This doesn't work. Flask generates links without the `/map` part.

**Comment by encukou** [comment]
Can't reproduce right now, but try adding a slash to the URL.

``` python
>>> urllib.parse.urljoin('https://honzajavorek.github.io/map', 'index.html')
'https://honzajavorek.github.io/index.html'
>>> urllib.parse.urljoin('https://honzajavorek.github.io/map/', 'index.html')
'https://honzajavorek.github.io/map/index.html'
```

**Comment by honzajavorek** [comment]
The correct way to solve this seems to be to set application root: https://stackoverflow.com/a/18967744/325365 However, this doesn't work with Flask-Frozen:

```
ValueError: Unexpected status '404 NOT FOUND' on URL /map/static/icon.png
```

I don't think this is Elsa issue.

**Comment by honzajavorek** [comment]
Filed as https://github.com/Frozen-Flask/Frozen-Flask/issues/92
