### ISSUE TITLE
A Minimal app example ? 

### ISSUE THREAD

**Issue by ufo911** [pyvec/elsa#62]
Can you add examples ? or documentation..

**Comment by hroncok** [comment]
This is the best we have now for docs: https://github.com/pyvec/elsa/blob/master/QUICKSTART.rst

Examples include:

https://github.com/fedora-python/fedoralovespython.org
https://github.com/pyladiescz/pyladies.cz
https://github.com/pyvec/python.cz
https://github.com/pyvec/pyvec.org
