### ISSUE TITLE
serve: Host 0.0.0.0 does not work on Windows

### ISSUE THREAD

**Issue by encukou** [pyvec/elsa#66]
I got a [report](https://github.com/pyvec/naucse.python.cz/pull/658) that `0.0.0.0`, [the host used for `serve`](https://github.com/pyvec/elsa/blob/5f503bc780c3ad6f8bc832adc8dc19e74ed4ffe2/elsa/_cli.py#L96) does not work on Windows.

@hroncok Is it there for a reason, or can we revert to Flask's default? Or switch the default to `127.0.0.1`?

**Comment by hroncok** [comment]
I don't remember the reason. I believe it was introduced when we forked Elsa from pyladies.cz.

**Comment by hroncok** [comment]
https://flask.palletsprojects.com/en/1.1.x/quickstart/#a-minimal-application

> If you run the server you will notice that the server is only accessible from your own computer, not from any other in the network. This is the default because in debugging mode a user of the application can execute arbitrary Python code on your computer.
> 
> If you have the debugger disabled or trust the users on your network, you can make the server publicly available simply by adding --host=0.0.0.0 to the command line:
> 
>     $ flask run --host=0.0.0.0
>
> This tells your operating system to listen on all public IPs.

**Comment by hroncok** [comment]
The docs here say to open localhost, not 0.0.0.0. I believe that should work on Windows as well.

It's Flask that should not tell you `Running on http://0.0.0.0:8003/` IMHO.

**Comment by encukou** [comment]
Right. Elsa technically does nothing wrong... but defaulting to `0.0.0.0` is not ideal. It's not a secure default.

In https://github.com/pyvec/elsa/pull/67 I switch to Flask's own default.
