### ISSUE TITLE
MimetypeMismatchWarning: Filename extension of 'CNAME'

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/elsa#7]
```
Generating HTML...
/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/elsa/_cli.py:17: MimetypeMismatchWarning: Filename extension of 'CNAME' (type application/octet-stream) does not match Content-Type: text/html; charset=utf-8
  freezer.freeze()
Setting up git...
```

**Comment by hroncok** [comment]
This is known (and absolutely OK). Feel free to propose code that would hide that warning for CNAME.

**Comment by honzajavorek** [comment]
OK. I got scared by it, because I thought it prevents deploy, but at the end I figured out GitHub Pages had unscheduled maintenance and deployment was paused by them 😥

**Comment by honzajavorek** [comment]
Why this got closed? Does it still appear in the output? I remember I used Elsa some time ago and it scared me again and I tried to solve it and googled out this my issue.

**Comment by hroncok** [comment]
I have a fix ready.
