### ISSUE TITLE
Hacktoberfest limits  🍄 🍄 🍄

### ISSUE THREAD

**Issue by encukou** [pyvec/elsa#88]
This repository is attracting many [spam pull requests] during [Hacktoberfest] 2020.

Due to the overwhelming number of PRs, we have limited interaction with this repository to existing contributors.
If you have a pull request, please request a pull the old-fashioned way: send the URL of your fork, and the branch name, to [encukou@gmail.com].
I'll merge manually or open a PR on your behalf.

If you found an issue, or want to do anything else we're disallowing this month, please e-mail the same address.

[spam pull requests]: https://github.com/pyvec/elsa/pulls?q=is%3Apr+is%3Aclosed
[Hacktoberfest]: https://hacktoberfest.digitalocean.com/
[encukou@gmail.com]: mailto:encukou@gmail.com

(And if we forget to take the message down at the end of the month,
please let us know as well!)

**Comment by encukou** [comment]
October is over for 2020.

**Comment by honzajavorek** [comment]
This is still pinned in the issues, I'll unpin it.
